### ISSUE TITLE
Minor typo: cliboard

### ISSUE THREAD

**Issue by hi5** [amate/Proxydomo#1]
Proxydomo64 - in lang\English.lng Line 44:

1024=Import from cliboard

`cliboard` should be `clipboard`

Keep up the good work :+1:

**Comment by amate** [comment]
v1.48 fixed
thx!

**Comment by hi5** [comment]
Thanks - found another similar typo in the context menu in the filter manager:
![menu in filter manager](https://cloud.githubusercontent.com/assets/1973899/6766589/6733da7c-d00c-11e4-8df4-0e35eb4c401f.png)

**Comment by amate** [comment]
v1.49 fixed
thx!!
