### ISSUE TITLE
SHA256 cert error

### ISSUE THREAD

**Issue by nhantrn** [amate/Proxydomo#12]
I tried the 2048bitRSA CA but browsers are giving me _Error code: sec_error_bad_signature_.

Also, sorry I don't speak Japanese and used online translator for the update log. I don't understand this one:

> ・SSLFilterでブラウザに吐くサーバーの証明書の署名にSHA256を使うようにした

Can you explain for me?

**Comment by amate** [comment]
Did not reproduce in my PC.

Mean to use SHA256 to sign the server certificate.
![img](http://farm9.staticflickr.com/8748/16896641240_fdf192ccc1_o.png)

okay if CA certificate that you generated in v1.51?

**Comment by nhantrn** [comment]
My mistake, I got it working now. However CPU usage seems higher than v1.51. Youtube.com loads very slow.

**Comment by amate** [comment]
Since the key is longer performance would have reduced.
Since changing the RSA to ECC in v1.53 performance will go up a little.

**Comment by nhantrn** [comment]
V1.53 is better, but still somewhat slow. Can you add a setting to choose between 1024bit and 2048bit when making CA?

I use Firefox mainly and Mozilla doesn't have strict policy against 1024bit CA yet.

**Comment by amate** [comment]
v1.54 implement

**Comment by nhantrn** [comment]
Thank you so much :+1: I hope I'm not bugging you too much :)
