### ISSUE TITLE
[feature request] New special replace \o and \i text codes

### ISSUE THREAD

**Issue by nhantrn** [amate/Proxydomo#13]
I'd like to propose two new replace text codes:

**\o** returns any requested url to just _domain.com_ without subdomain or www
For example,
 \o of
_sub1.domain.com_ ==> _domain.com_
_sub1.sub2.domain.com_ ==> _domain.com_
_www.domain.com_ ==> _domain.com_
etc.

---

**\i** returns string _http_ or _https_ of connection protocol type

\i can be used to load secure/non-secure resources to current page type. For example,

```
Replace = "<link href="\i://local.ptron/userstyles/\o.css" type="text/css"></head>"
```

**Comment by amate** [comment]
The first can be solved by using the "$URL".

`[Patterns]`
`Name = "test1"`
`Active = TRUE`
`Multi = FALSE`
`URL = ""`
`Bounds = ""`
`Limit = 128`
`Match = "match$URL(http(s|)://*(.|)([^.]+.[^./]+)\0/*)"`
`Replace = "\0"`

The second can be solved by as follows.
`Replace = "<link href="//local.ptron/userstyles/\o.css" type="text/css"></head>"`

**Comment by nhantrn** [comment]
1. Thx, didn't know about this.
2. I totally forgot about this trick. Thx!
