### ISSUE TITLE
Proxydomo limit download speed down to ~500kb/s

### ISSUE THREAD

**Issue by nhantrn** [amate/Proxydomo#14]
Download speed going through Proxydomo v1.54 is is throttled down to ~500kb/s. I tested on all browser with the same result. This is a major problem, need fix.

**Comment by amate** [comment]
Did not reproduce in my PC.
Proxydomo does not limit the download speed.
I have the download speed of 2.0MB/s in my environment.
![dlspeed](https://cloud.githubusercontent.com/assets/647810/7159785/958baad2-e3bf-11e4-92b5-429ea9533d22.png)
http://windows.microsoft.com/en-us/windows/preview-iso-update-1503

Such a thing happens also in bypass?

**Comment by nhantrn** [comment]
Download speed with Proxydomo.
![Image 1](http://i.imgur.com/sYvFNvZ.jpg)

With Proxydmo bypassed.
![Image 3](http://i.imgur.com/rLFrnGI.jpg)

Without Proxydomo.
![Image 2](http://i.imgur.com/TLpkEex.jpg)

I'm using Windows 7 x32.

**Comment by nhantrn** [comment]
Ok this is weird, I found that downloads on HTTP are throttled. However, downloads on HTTPS are not throttled.

**Comment by amate** [comment]
I made a debug version. please try it.
http://1drv.ms/1GQsFyN

**Comment by nhantrn** [comment]
Ok, I tried it. Download still throttled. Do you need the log file?

**Comment by amate** [comment]
I made a debug version2. please try it.
http://1drv.ms/1Hg2al3
I don't need the log file for now.

**Comment by mas91180** [comment]
my two coins - 1.55_debug2 gives me around 2.4 MB/s in bypass mode, while with good old Proxomitron in filter mode I have 5.6 MB/s. Let me know if you need any additional info on this matter.
Thanks for you work.

**Comment by amate** [comment]
I made a release version3. please try it.
http://1drv.ms/1cFqxgL
This is because I don't have built Proxydomo in the optimization

**Comment by mas91180** [comment]
no changes for me with version3 - the same 2+ times speed difference.

**Comment by nhantrn** [comment]
For me, debug2 peak @~700KB/s. Debug3 back down to ~500KB/s.

**Comment by amate** [comment]
I made a release version4. please try it.
http://1drv.ms/1yCuXyM
Can not be anymore if no good at this.

**Comment by amate** [comment]
I made a release version4. please try it.
http://1drv.ms/1yCuXyM
Can not be anymore if no good at this.

**Comment by nhantrn** [comment]
Same, still low speed.

Do you know what cause the slow down? Why is it only affecting downloads from HTTP and not HTTPS?

**Comment by amate** [comment]
I made a debug version5. please try it.
http://1drv.ms/1DUz49F
Caution! this version is High Memory Usage.
Download speed, please look at the Resource Monitor.

It may also under the influence of anti-virus software.

**Comment by nhantrn** [comment]
Download speed is ~750KB/s for debug5.

**Comment by amate** [comment]
How much upload speed?
Upload must begin after the download is finished.

**Comment by nhantrn** [comment]
I don't know of another upload service that is HTTP-only, so I do not know if my test is accurate.

But I tried http://shared.com upload. Upload speed with Proxydomo is about the same compare to with no Proxydomo. I got around ~365KB/s upload. However, I think shared.com limit speed for free users. So I cannot be sure this is accurate.

**Comment by amate** [comment]
"Upload" means speed between the browser and the Proxydomo.
![upload](https://cloud.githubusercontent.com/assets/647810/7217832/1fd18bd4-e682-11e4-85c3-202612dac4ad.png)
How much speed between the browser and the Proxydomo when you download a file?

**Comment by nhantrn** [comment]
![2015-04-18_204700](https://cloud.githubusercontent.com/assets/3202654/7218065/c3aef1ae-e60c-11e4-8b1f-c30299e4e842.jpg)

**Comment by amate** [comment]
In the image Proxydomo is downloading in 6MB/s.
https://youtu.be/FfDzQ0RamYU
Should upload to the browser begins after the end of the download in Proxydomo side as the video.

**Comment by nhantrn** [comment]
Here's the video i recorded: https://vid.me/ON3E
It got up to 9MB/s, but I assume this is a wrong reading. The real download speed of the file was ~350KB/s. As you can see in the video, it went up to 7 minutes and still not finish downloading.

**Comment by nhantrn** [comment]
After doing some testing, I've found the trouble causing this speed slow down.

First of, I'm really sorry for causing you trouble because this is a local issue that doesn't involved Proxydomo. But in the process, I've also found something interesting with the original Proxomitron.

Ok, I've this small program that monitor my home network traffic called Networx (https://www.softperfect.com/products/networx/). In its setting, there's an option "Ignore local traffic  within LAN"
![image](https://cloud.githubusercontent.com/assets/3202654/7225070/4f41b11a-e6ef-11e4-98b3-755f4b7806bc.png)

When that setting is on, it slows down Proxymodo's speed. When I turn this setting off, Proxydomo speed is normal.

I haven't notice this before because when I still use the original Proxomitron, Networx doesn't affect Proxomitron's speed at all. And I've been using both program for many years. Somehow Proxomitron is able to classify itself as non-local, so Networx doesn't detect it.

Would it be possible to make Proxydomo hides itself from Networx?

**Comment by amate** [comment]
I made a debug version6. please try it.
http://1drv.ms/1Q8Pocc
It would be resolved perhaps in this version.

**Comment by nhantrn** [comment]
Still same if  _Ignore local traffic_ in on in Networx setting.

**Comment by amate** [comment]
I made a debug version7. please try it.
http://1drv.ms/1D9MRnX
In this version Proxydomo use the same winsock2.0 as Proxomitron's using.

**Comment by nhantrn** [comment]
Libreoffice starts downloading ~650KB/s, then about one-thirdway through, reached ~2.0MB/s.
Windows10 starts out at ~650KB/s, goes to 1.8MB/s for a little bit, then drop back down to ~650KB/s.

It's working, but unstable.

**Comment by amate** [comment]
I made a debug version8. please try it.
http://1drv.ms/1Pj6J0D
Would resolve finally.

**Comment by nhantrn** [comment]
I'm getting 2.5 MB/s with Networx local traffic mode. If local traffic monitor is off, I'm getting my maximum speed 4 MB/s!

And I notice Proxydomo's filtering speed is much faster than Proxomitron in general. Proxomitron max out at 1.8 MB/s download on my pc with Networx mode on or off, whereas your program could give me maximum speed.

Nice job amate :+1:  Scott Lemmon would have been impressed with you!

**Comment by amate** [comment]
v1.55 fixed
