### ISSUE TITLE
[If possible] Please consider fixing this filter bug

### ISSUE THREAD

**Issue by anatasiajp** [amate/Proxydomo#15]
Skidi's filter pack is a famous filter pack for Proxomitron for a long time, but I found that I cannot use this pack with Proxydomo because after import this pack into Proxydomo, Proxydomo simply stop working.

http://www.prxbx.com/forums/showthread.php?tid=1870

What I did ?
I extracted this pack into Proxydomo folder, open sidki_2011-12-22rc1.ptron with Notepad and copy all content and then return to Proxodomo, import, everything is okay but when I go to a random website, Proxydomo stop working.

I know that might not be a bug, but at least we should know why that happen.

**Comment by nhantrn** [comment]
There are some unimplemented commands (http://www31.atwiki.jp/lafe/pages/44.html#id_bc0e77d1). Looking through sidki list, there several _$ADDLST, $DTM, and \d_ so I suspect those would cause some errors. Uncheck those rules and see if it works?

**Comment by cattleyavns** [comment]
Okay, I will try your suggests now and will report right after.

**Comment by amate** [comment]
I have solved some of the problems with v1.56.
However, it will not work perfectly still so filter is complex.
