### ISSUE TITLE
Web filtering character encoding bug

### ISSUE THREAD

**Issue by nhantrn** [amate/Proxydomo#16]
Web filtering is messing up the character encoding on https://www.commafeed.com/#/feeds/view/category/all

![2015-04-28_004928](https://cloud.githubusercontent.com/assets/3202654/7365017/33a9cc1e-ed41-11e4-95aa-baab75713e57.jpg)
![2015-04-28_005032](https://cloud.githubusercontent.com/assets/3202654/7365020/36ebcd28-ed41-11e4-9701-5279fe75ac92.jpg)

CSS character code example.

```
.glyphicon-cog:before{
    content:"\e019"
}
```

**Comment by amate** [comment]
v1.57 fixed
thx!
