### ISSUE TITLE
Launching from start up folder doesn't show icon bug

### ISSUE THREAD

**Issue by nhantrn** [amate/Proxydomo#17]
I have Proxydomo 1.58 in the start up folder. It launches, but shows no icon in the tray.

Also, maybe add an option to launch when login?

**Comment by amate** [comment]
v1.59 fixed

**Comment by nhantrn** [comment]
The 32bit binary download is still v1.58.

**Comment by amate** [comment]
I'm sorry. 
The file has been replaced.
