### ISSUE TITLE
Netflix connection error

### ISSUE THREAD

**Issue by nhantrn** [amate/Proxydomo#18]
netflix.com is giving an ASN signer error.

**Comment by amate** [comment]
The first time I accessed the page, and the dialog was displayed.
However It was no longer displayed.
It is displayed even now?

**Comment by nhantrn** [comment]
Yes it still does.
When I go to netflix.com, it's non-secure by default. Then it redirects to https page. So I guess that's what causing the error dialog to display.

I also notice that whenever any non-secure site loads in secure contents, the error dialog pop up.

**Comment by amate** [comment]
Can you upload a screenshot of the error dialog?

**Comment by nhantrn** [comment]
![2015-05-17_145311](https://cloud.githubusercontent.com/assets/3202654/7672357/93f2a09c-fca4-11e4-82f9-f9f100b6438b.jpg)
![2015-05-17_145329](https://cloud.githubusercontent.com/assets/3202654/7672358/96208d2a-fca4-11e4-8796-9fd970a72416.jpg)

**Comment by amate** [comment]
I made a debug version1.60.1. please try it.
http://1drv.ms/1IGRzBY
Please upload a info.log after the error dialog is displayed.

**Comment by nhantrn** [comment]
https://www.dropbox.com/s/6wnmg6sggdstjyw/info.log?dl=1

**Comment by nhantrn** [comment]
https://www.dropbox.com/s/6wnmg6sggdstjyw/info.log?dl=1

**Comment by amate** [comment]
Please try to open https://netflix.com/ in IE, and open the page with proxydomo.

**Comment by nhantrn** [comment]
https://www.dropbox.com/s/6wnmg6sggdstjyw/info.log?dl=1

**Comment by amate** [comment]
If you open the https://netflix.com/ in InternetExplorer you do not set the proxy, 
then "VeriSign Class 3 Public Primary Certification Authority - G3" is enabled and the error dialog will be no longer displayed.

**Comment by amate** [comment]
v1.64 fixed
