### ISSUE TITLE
"Building" is not working

### ISSUE THREAD

**Issue by 0rt** [amate/Proxydomo#19]
I try to build you proxydomo, following you instruction, since you don't mention version, I download the latest verision, 
boost 1.59.0
wolfssl 3.6.6
icu4c-55_1
WTL90_4140_final
Put it to folder your defined, built boost using your command, then built proxydomo with VS2015. Everything looked fine until got multiple linking error, all of them are about ssl.obj, did you meet that before?

**Comment by amate** [comment]
Perhaps I estimated that the project of wolfssl is not loaded.

Remove the wolfssl from Proxydomo of Solution Explorer.
![1](https://cloud.githubusercontent.com/assets/647810/9762064/d6a919ba-573b-11e5-9d3e-b2f609d35c05.PNG)

Please add wolfssl\wolfssl.vcxproj using the "Add existing project".
![2](https://cloud.githubusercontent.com/assets/647810/9762096/07698936-573c-11e5-92d1-d56edc0b8b8c.PNG)
![3](https://cloud.githubusercontent.com/assets/647810/9762098/0ad51cd4-573c-11e5-8fb3-187859367b23.PNG)

Rewrite the definition of the preprocessor in the following contents in the property page of wolfssl.

// for Debug/Release Win32
WOLFSSL_CERT_GEN
WOLFSSL_KEY_GEN
HAVE_AESGCM
HAVE_AESCCM
HAVE_CAMELLIA
HAVE_ECC
HAVE_OCSP
HAVE_TLS_EXTENSIONS
HAVE_SESSION_TICKET
HAVE_SNI
HAVE_SECURE_RENEGOTIATION
HAVE_SUPPORTED_CURVES
WOLFSSL_RIPEMD
WOLFSSL_SHA384
WOLFSSL_SHA512
NO_PSK

// for Debug/Release x64
WOLFSSL_CERT_GEN
WOLFSSL_KEY_GEN
HAVE_AESGCM
HAVE_AESCCM
HAVE_CAMELLIA
HAVE_ECC
HAVE_OCSP
WOLFSSL_AESNI
HAVE_TLS_EXTENSIONS
HAVE_SESSION_TICKET
HAVE_SNI
HAVE_SECURE_RENEGOTIATION
HAVE_SUPPORTED_CURVES
WOLFSSL_RIPEMD
WOLFSSL_SHA384
WOLFSSL_SHA512
NO_PSK

![4](https://cloud.githubusercontent.com/assets/647810/9762148/623b41ba-573c-11e5-8763-69b38e93bf23.PNG)

Please put a check in the wolfssl of "dependent destination" in the setting of project dependencies.
![5](https://cloud.githubusercontent.com/assets/647810/9762414/4f9f06b6-573e-11e5-9836-dc9b0f598c61.PNG)
![6](https://cloud.githubusercontent.com/assets/647810/9762175/be64904a-573c-11e5-8d7f-4951b21954cb.PNG)

Please add wolfssl to reference of the Proxydomo.
![7](https://cloud.githubusercontent.com/assets/647810/9762399/3b1019f6-573e-11e5-8b64-b6ca9ccea70d.PNG)
![8](https://cloud.githubusercontent.com/assets/647810/9762401/3b8a8d08-573e-11e5-9c5e-7bcc042492e7.PNG)

Updated command line for vs2015
// x86
b2.exe install -j 4 --prefix=lib toolset=msvc-14.0 runtime-link=static --with-thread --with-date_time --with-timer --with-log
// x64
b2.exe install -j 4 --prefix=lib64 toolset=msvc-14.0 runtime-link=static address-model=64 --with-thread --with-date_time --with-timer --with-log

This should pass through the build.

**Comment by 0rt** [comment]
詳しく説明いただいてありがとうございます。
おかしいですね、最新のソースをダウンロードしてから、新しいフォルダーでもう一回ビールしましたら、また同じエラーが出てきます。
明日もう一回説明通りやってみます。

**Comment by 0rt** [comment]
```
1>LINK : warning LNK4098: defaultlib 'MSVCRT' は他のライブラリの使用と競合しています。/NODEFAULTLIB:library を使用してください。
1>wolfssl.lib(ssl.obj) : error LNK2001: 外部シンボル "__imp__strncpy" は未解決です。
1>wolfssl.lib(ssl.obj) : error LNK2001: 外部シンボル "__imp__rewind" は未解決です。
1>wolfssl.lib(ssl.obj) : error LNK2001: 外部シンボル "__imp__strncat" は未解決です。
1>wolfssl.lib(ssl.obj) : error LNK2001: 外部シンボル "__imp__fread" は未解決です。
1>wolfssl.lib(asn.obj) : error LNK2001: 外部シンボル "__imp___mktime64" は未解決です。
1>MSVCRT.lib(_chandler4gs_.obj) : error LNK2001: 外部シンボル "__except_handler4_common" は未解決です。
1>D:\code\Proxydomo\Release\Proxydomo.exe : fatal error LNK1120: 6 件の未解決の外部参照
```

わざわざ日本語バージョンのMSVC2015に替えてやり直しますが。同じエラーが出てきます。
また、

```
#include <wx/thread.h> 
```

このようなincludeがありますが、Windows Widgetが必要でしょうか？

**Comment by amate** [comment]
wolfsslのプロパティページ C/C++ -> コード生成
ランタイムライブラリ : マルチスレッド デバッグ DLL (/MDd)
を マルチスレッド デバッグ (/MTd) へ変更してみてください

wxWidgetsは使っていないので必要ないです

**Comment by 0rt** [comment]
ありがとうございました。今回は完済しました。
