### ISSUE TITLE
HTTPS high cpu load

### ISSUE THREAD

**Issue by nhantrn** [amate/Proxydomo#2]
Hi,
When Proxydomo filters https pages, the CPU load is very high on my laptop that the fan kicks on. This doesn't happen on non-secure http or https without Proxydomo. Is it possible to reduce cpu usage on HTTPS connection?

**Comment by amate** [comment]
SSLFilter it would be difficult to reduce the CPU usage because it uses the CPU to decrypt and encrypt.

**Comment by nhantrn** [comment]
I don't know much about SSL encryptions, so excuse my questions. But how does browsers handle SSL decryption/encryption without much cpu usage than Proxydomo? Maybe you could use browsers method to encrypt/decrypt SSL in Proxydomo?

**Comment by amate** [comment]
Browser can be processed quickly because it is using the CPU instruction set such as AES-NI.
However, GnuTLS which is used to encrypt and decrypt is slow because it does not use the AES-NI in for windows.

**Comment by nhantrn** [comment]
I checked http://www.gnutls.org/ but couldn't find any mention of AES-NI being work on for Windows. I'm not familiar with the technicalities, but Is there anything in version 3.4 plan(https://gitlab.com/gnutls/gnutls/wikis/Plan3_4)  that can be used to make decrypting/encrypting https more efficient on Windows?

**Comment by amate** [comment]
GnuTLS would not be expected in the optimization for Windows.
I will consider wolfssl etc.

**Comment by nhantrn** [comment]
Great work on v1.50. WolfSSL is much better. CPU workload fairly OK.
