### ISSUE TITLE
先日のビルドしたProxydomoにはHTTPS問題がありますようです

### ISSUE THREAD

**Issue by 0rt** [amate/Proxydomo#20]
![2015-09-11_212129](https://cloud.githubusercontent.com/assets/822795/9815891/010d9f1e-58cc-11e5-9d6a-9092868b0215.png)
１．時々OCSPエラーが出てくる。
２．Gmail、Github、Googleとか大分のHTTPS接続が問題ありませんが、下のHTTPSサイトがcaファイルを導入しましたが、開けません。
https://www.newszeit.com/

バージョン1.61は問題ありませんようです、以上の問題は、わたくしのビルドのバラメーターの問題ですか、それとも、1.61の後なにか変えて起こした不具合はわたくしには分かりませんが、一応知らせてまいりました。

**Comment by 0rt** [comment]
```
/*
			ret = wolfSSL_CTX_EnableOCSP(g_sslclientCtx, WOLFSSL_OCSP_CHECKALL);
			ATLASSERT(ret == SSL_SUCCESS);
*/
```
reverted above commit will fixed it.
https://github.com/amate/Proxydomo/blob/7c2f8956cb1b3c01caa49fb00ef0dc7c8f367c61/Proxydomo/ssl.cpp

**Comment by amate** [comment]
最新のソースで追加された
・wolfSSL_CTX_EnableOCSPをお試しで追加
が問題のようです
v1.61のソースでビルドしてみてください

**Comment by 0rt** [comment]
やっぱりこちらの何かパラメーターの問題もありますと思います。
Gitで1.61のソースでビルドしても、その  https://www.newszeit.com  は開けません。
本当に手をあげました＞＿＜。

wolfSSL 3.6.0バージョンがダウンロードができませんでしたので、wolfSSL 3.6.6をお使いしました。問題になりますでしょうか？

＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊
OCSP警告はしばらく出てきません。使い続けますので、明日報告します

**Comment by 0rt** [comment]
今日、1.63のソースでまたビルドしました。あの https://www.newszeit.com は依然として開けませんでした。Debug ビルドのEXEとWolfsslのlibファイルアップロードして、もし時間があればとちょっとご覧ください。
http://1drv.ms/1MbIeRH

ソース：
https://github.com/0rt/Proxydomo/commits/master
ソースは全く同じだと思います。ただ、includeとlibrary pathに私のを追加し、HAVE_OCSPを消しましただけと思います。（HAVE_OCSPは https://www.newszeit.com に関係ありませんのようです）

**Comment by amate** [comment]
wolfssl v3.6.6ではプリプロセッサの定義に
WOLFSSL_STATIC_RSA
を追加してみてください

**Comment by 0rt** [comment]
素早く返事してくださってありがとうございます。やはりwolfssl 3．6.6の問題です。WOLFSSL_STATIC_RSAを追加したビルドは無事に https://www.newszeit.com 開きました。
