### ISSUE TITLE
Headers enhance

### ISSUE THREAD

**Issue by 0rt** [amate/Proxydomo#22]
1. should allow users add headers, not only modify headers.
   Useful when add value like http-only cookie, which could only be changed by http headers...
   Set-Cookie: val=foo;
2. Multi line headers.
   I can't find a way to modify 2 Set-Cookie at once.... the following link has two set-cookie headers (because one set-cookie header can only set 1 cookie value):

http://valf.atm.youku.com/vf?vip=0&site=1&rt=MHwxNDQyMTY1ODA3OTcxfFhOekl3T0Rnd09UZ3c=&p=1&vl=247&fu=0&ct=e&cs=2121&paid=0&s=&td=1&sid=844216579585710c952bf&v=180220245&wintype=exterior&u=129173756&vs=1.0&rst=flv&partnerid=null&dq=auto&emb=NTkuNDIuMTg4Ljg2AjE4MDIyMDI0NQIC&os=Windows&osv=10&d=0&bt=pc&aw=w&ti=%E3%80%90%E4%B8%AD%E6%96%87%E5%AD%97%E5%B9%95%E3%80%91%E6%B3%A2%E6%B3%A2%E7%BB%B4%E5%A5%87YouTube%E7%82%B9%E5%87%BB%E6%9C%80%E9%AB%98%E8%A7%86%E9%A2%91%EF%BC%8C%E5%8E%86%E5%B9%B4%E7%BB%8F%E5%85%B8%E9%87%87%E8%AE%BF&k=%E6%B3%A2%E6%B3%A2%E7%BB%B4%E5%A5%87%7C%E9%82%93%E8%82%AF%7C%E5%B8%95%E5%85%8B%7C%E5%90%89%E8%AF%BA%E6%AF%94%E5%88%A9%7CNBA|%E9%A9%AC%E5%88%BA

in RAW value, it's like 
Set-Cookie: foo=1;\r\n
Set-Cookie: bar=2;\r\n

But the following rule is not working.

```
[HTTP headers]
Key = "Set-Cookie: set-cookie"
In = TRUE
Out = FALSE
Active = TRUE
Multi = TRUE
URL = "valf.atm.youku.com"
Replace = " foo=1;\r\n Set-Cookie: bar=2;\r\n"
```

**Comment by amate** [comment]
1. 送信/受信ヘッダに"ヘッダ名"で指定されたヘッダが存在しなかった場合は
   マッチングパターンでマッチすればヘッダが追加されます
2. グローバル変数と$TSTを用いて疑似的に同時に変更することが可能です

```
[HTTP headers]
Key = "Set-Cookie: test1"
In = TRUE
Out = FALSE
Version = ""
Author = ""
Comment = ""
Active = TRUE
Multi = FALSE
URL = ""
Bounds = ""
Limit = 2000
Match = "(^$TST(multisetcookie=1|2))$SET(multisetcookie=1)$SET(0=foo=1;)"
        "|(^$TST(multisetcookie=2))$SET(multisetcookie=2)$SET(0=bar=2;)"
        "|$SET(0=)"
Replace = "\0"
```

1行目のSet-Cookieの内容が"foo=1;"
2行目のSet-Cookieの内容が"bar=2;"
3行目以降のSet-Cookieは削除されます

**Comment by 0rt** [comment]
変数と＄TSTを使ってもやはり制限がありますようです。
例えば、あるサイトが本当のlinkを開くには、二回クリックしなければいけない。ユーザ一回目クリックしてから、広告を開けます、同時に、２つのset-cookieします。それでは今度同じlinkをクリックしたとき、本当のアドレスへ行きます。

この$TSTはもともと2行のset-cookieがなくてはなりませんので、使われません。

In English:

foo.com/         (didn't have 2 set-cookie)
open a link on foo.com/bar.php, the first time will redirect the browser to an ads page, and 2 set-cookie

I want to 2 lines of set-cookie at the homepage, the currently proxydomo won't allow that...

**Comment by amate** [comment]
値が決まっているならそもそも送信ヘッダのCookieのほうを改変するとか
$ADDHEADERコマンドなりを新設した場合、値の修正と追加が同時に起こるのが煩雑に思える
<start>のように、マッチに<addheader>があれば、Replaceの値を追加指示する仕様にしたほうがいいかな

**Comment by cashlex** [comment]
PLEASE I CANNOT UNDERSTAND CHINA PLEASE ADD ENGLISH TO IT THANKS 

PLEASE CAN YOU ADD MAKE A VIDEO ON HOW TO COMPILE THIS APP I GOT 1347 ERRORS AM CONFUSE PLEASE I NEED HELP AM FROM NIGERIA

let me try to translate it to Chinese using translator.google.com

请我不明白中国请加ENGLISH TO IT谢谢

请你能加入进行视频如何编译这个程序我得到1347错误AM混淆请我需要帮助AM尼日利亚

我甚至下载SRC完整的文件从https://onedrive.live.com/?id=8830DE058EEDFF85!10224&cid=8830DE058EEDFF85&group=0，仍然没有进展我需要帮助，谢谢
