### ISSUE TITLE
REDIR

### ISSUE THREAD

**Issue by Stone-D** [amate/Proxydomo#23]
I run a school lab, and I have been using Proxomitron and now Proxydomo to censor and control usage. With http:// sites, I can redirect to a local htm page - however, I can't do it with https. The browser receives a zero byte 'download' and just stops. Not very elegant.

**http://**www.facebook.com/ redirects to _http://local.ptron/Disabled.htm_ just fine.
**https://**www.facebook.com/ does not.

Is it really not possible right now, or am I doing something wrong? If not possible, could you possibly fix it so I can use REDIR like this for https?

```
      <filter>
        <Active>true</Active>
        <title>Block 0 - Disable ALL (out)</title>
        <filterType>1</filterType>
        <headerName>URL</headerName>
        <multipleMatches>false</multipleMatches>
        <windowWidth>256</windowWidth>
        <boundsPattern/>
        <urlPattern>\0</urlPattern>
        <matchPattern>(http(s|)://)\1\2</matchPattern>
        <replacePattern>$RDIR(\1local.ptron/Disabled.htm)$LOG(R[HDR:URL] Block 0 - ALL)</replacePattern>
      </filter>
```

**Comment by amate** [comment]
v1.65 fixed

**Comment by Stone-D** [comment]
That was fast. It works perfectly now, **many** thanks!

**Comment by Stone-D** [comment]
Edited: Bad Report

**Comment by Stone-D** [comment]
Never mind, my bad. I apologize. The networked computer I had been using was corrupted and needs to be re-imaged.
Now I just need to figure out how to stop youtube from re-using existing connections, but that's a filter problem.  :)
