### ISSUE TITLE
[Bug?] About "&"

### ISSUE THREAD

**Issue by sanitoT** [amate/Proxydomo#27]
Ver 1.67

[Patterns]
Replace = "(\1)"

Test text = "foo1bar2foo3bar4"

| Match | Proxomitron | Proxydomo |
| --- | --- | --- |
| (bar&*3)\1 | foo1(bar2foo3)bar4 | foo1(bar2foo3)bar4 |
| (*3&bar)\1 | foo1(bar2foo3)bar4 | foo1(bar)bar4 |

**Comment by amate** [comment]
v1.68 fixed
thx!
