### ISSUE TITLE
elements.polymer-project.org connection error

### ISSUE THREAD

**Issue by nhantrn** [amate/Proxydomo#28]
I'm getting a **ssl_error_rx_malformed_handshake** on https://elements.polymer-project.org/

**Comment by amate** [comment]
Since the size of the certificate that is sent is large it seems to get an error.
Because do not know how to fix, it would be difficult to fix.

**Comment by amate** [comment]
You can connect the site If you add "elements.polymer-project.org" to Bypass.txt in version 1.71.

**Comment by cashlex** [comment]
SORRY FOR MULTI POSTING I NEED HELP

PLEASE I CANNOT UNDERSTAND CHINA PLEASE ADD ENGLISH TO IT THANKS

PLEASE CAN YOU ADD MAKE A VIDEO ON HOW TO COMPILE THIS APP I GOT 1347 ERRORS I CHANGED FROM V2015 ENTERPRISE TO V2015 COMMUNITY STILL THE SAME ERROR
AM CONFUSE PLEASE I NEED HELP AM FROM NIGERIA

I EVEN DOWNLOAD THE SRC FULL FILE FROM https://onedrive.live.com/?id=8830DE058EEDFF85!10224&cid=8830DE058EEDFF85&group=0 AND STILL NO PROGRESS I NEED HELP THANKS

let me try to translate it to Chinese using translator.google.com

HI GOOD DAY TO ALL AM CASHLEX
请我不明白中国请加ENGLISH TO IT谢谢

请你能加入进行视频如何编译这个程序我得到1347错误，我改变从V2015企业到V2015社会仍然出现同样的错误
AM混淆请我需要帮助AM尼日利亚

我甚至下载SRC完整的文件从https://onedrive.live.com/?id=8830DE058EEDFF85!10224&cid=8830DE058EEDFF85&group=0，仍然没有进展我需要帮助，谢谢
