### ISSUE TITLE
Ghost connection monitor entries

### ISSUE THREAD

**Issue by Stone-D** [amate/Proxydomo#29]
See the screenshot. The 'Abort' button has no effect. Are these connections still valid or are they some kind of logging glitch? The requesting computers have long since been shut down.

![clipboard image](https://cloud.githubusercontent.com/assets/522690/11580443/1826f9ae-9a6a-11e5-9a07-cf6641bdfabe.jpg)

**Comment by amate** [comment]
v1.75 fixed
