### ISSUE TITLE
Dialog font

### ISSUE THREAD

**Issue by adoxa** [amate/Proxydomo#3]
Would it be possible for all the dialogs to use `MS Shell Dlg` as the font? That would look much better for us English users.

**Comment by adoxa** [comment]
Used ResHacker to change it and discovered a few things need to be resized:
About: made 10 units bigger (there's also a typo: GUN->GNU);
Proxymodo: two units bigger (making all the filter checkboxes 77 units).

**Comment by adoxa** [comment]
Used ResHacker to change it and discovered a few things need to be resized:
About: made 10 units bigger (there's also a typo: GUN->GNU);
Proxymodo: two units bigger (making all the filter checkboxes 77 units).

**Comment by adoxa** [comment]
Used ResHacker to change it and discovered a few things need to be resized:
About: made 10 units bigger (there's also a typo: GUN->GNU);
Proxymodo: two units bigger (making all the filter checkboxes 77 units).

**Comment by adoxa** [comment]
Used ResHacker to change it and discovered a few things need to be resized:
About: made 10 units bigger (there's also a typo: GUN->GNU);
Proxymodo: two units bigger (making all the filter checkboxes 77 units).

**Comment by adoxa** [comment]
Used ResHacker to change it and discovered a few things need to be resized:
About: made 10 units bigger (there's also a typo: GUN->GNU);
Proxymodo: two units bigger (making all the filter checkboxes 77 units).

**Comment by amate** [comment]
v1.50 fixed
thx!

**Comment by adoxa** [comment]
That's looking a bit better, thanks (and for my other issues, as well).  However, "GPL" is still chopped off in the About, so everything there should be adjusted by 7 units.

**Comment by amate** [comment]
v1.51 fixed
thx!!
