### ISSUE TITLE
Request: Certificate Error Automation

### ISSUE THREAD

**Issue by Stone-D** [amate/Proxydomo#31]
Could you please add an option to auto-accept or auto-deny certificate errors such as the one shown in this screenshot?

![proxydomoca-01](https://cloud.githubusercontent.com/assets/522690/12251832/80a55d1e-b904-11e5-98f0-f6b0309c176f.png)

 I've made a mockup Options dialog to show you what I mean:

![proxydomoca-02](https://cloud.githubusercontent.com/assets/522690/12251842/90d35d94-b904-11e5-83c6-917c21e186a0.png)

The dropdown could have 'Accept', 'Deny', and, if easy to implement, 'Accept in $LIST'.

The error log could also show only errors, or both:

GOOD: google.com
ROOT FAILURE: something.org
PEER SUBJECT NAME MISMATCH: another.org

**Comment by amate** [comment]
v1.79 implementation (AllowSSLServerHostList.txt)
I won't implement the GUI.

**Comment by Stone-D** [comment]
Awesome, thank you.
