### ISSUE TITLE
IE 8 on WinXP SP3 can't connect to ssl

### ISSUE THREAD

**Issue by WRFan** [amate/Proxydomo#32]
IE 8 on WinXP can't connect. I seem to have a similar issue as this one:

https://github.com/amate/Proxydomo/issues/9

Same problem - connection is just cut off. SSL sites only. Doesn't happen on Win10 (IE 11), just on WinXP. If I connect to an SSL site directly using IE, then switch on proxydomo, it works, but just for that particular site, and only until browser is restarted.

Another issue: The header name field (filters) is too short, I couldn't insert long headers like "Access-Control-Allow-Origin" until I increased its size using a resource hacker.

**Comment by amate** [comment]
![default](https://cloud.githubusercontent.com/assets/647810/14405417/afadf6c4-fec9-11e5-959d-0b803d5b80f8.PNG)
Please try to generate RSA 1024bit private key.

I will fix the problem of the narrow header name filed in the next version.

**Comment by WRFan** [comment]
I tried the new version, it's not working either. I am using my own RSA 1024bit certificate, but I tried to generate all possible certificates by your programme too, but they are not working either. It's IE8 problem, because I tried K-meleon browser on WinXP and Proxydomo is working fine. As I said, it's working in IE11 (on Win10) too, it's just IE8 that fails for ssl pages when I use Proxydomo as proxy. It's working with the original Proxomitron. Maybe it has something to do with the certificate you are creating on the fly when accessing an ssl page? This certificate is not needed in IE, IE has less restrictions than Mozilla browsers. Could you maybe add an option to disable certificate chain generation? All versions of IE accept self-generated CA certificates as long as they are trusted and don't complain about anything else, so this additional certificate Proxydomo is generating is a useless waste on resources, it's only needed for Firefox etc.

**Comment by WRFan** [comment]
I tried the new version, it's not working either. I am using my own RSA 1024bit certificate, but I tried to generate all possible certificates by your programme too, but they are not working either. It's IE8 problem, because I tried K-meleon browser on WinXP and Proxydomo is working fine. As I said, it's working in IE11 (on Win10) too, it's just IE8 that fails for ssl pages when I use Proxydomo as proxy. It's working with the original Proxomitron. Maybe it has something to do with the certificate you are creating on the fly when accessing an ssl page? This certificate is not needed in IE, IE has less restrictions than Mozilla browsers. Could you maybe add an option to disable certificate chain generation? All versions of IE accept self-generated CA certificates as long as they are trusted and don't complain about anything else, so this additional certificate Proxydomo is generating is a useless waste on resources, it's only needed for Firefox etc.

**Comment by amate** [comment]
It seems IE can not connect to Proxydomo because IE is using too old encryption.
$FILTER (false) switch the connection to the tunnel mode.
Please try to import the following filter.

```
[HTTP headers]
Key = "URL: https ie 8  bypass"
In = FALSE
Out = TRUE
Version = ""
Author = ""
Comment = ""
Active = TRUE
Multi = FALSE
URL = "$URL(https://*)$OHDR(User-Agent:Mozilla/4.0*)$FILTER(false)"
Bounds = ""
Limit = 2000
Match = ""
Replace = ""
```

**Comment by WRFan** [comment]
I already tried such a filter before, but it doesn't work either. Besides, bypassing SSL would make Proxydomo useless to me, as this is exactly the reason why I switched away from Proxomitron, cause it was throwing SSL errors all the time, making filtering SSL pages impossible

**Comment by amate** [comment]
When I try to connect the IE to the SSL site. I was able to connect to the page.
![default](https://cloud.githubusercontent.com/assets/647810/14863495/d3f9e896-0cf0-11e6-8fb9-27e0c3fb0f3f.PNG)
https://www.ssllabs.com/ssltest/viewMyClient.html

Reproduction is no longer possible.

**Comment by WRFan** [comment]
All right, I got it.

HKLM\SOFTWARE\Policies\Microsoft\Windows\CurrentVersion\Internet Settings
SecureProtocols DWORD -> a0 hex
