### ISSUE TITLE
WebSockets issue

### ISSUE THREAD

**Issue by mas91180** [amate/Proxydomo#33]
Hi Amate, there seems to be problems with recent versions and websockets: WebSocket connection to 'ws://12.34.56.78:443/' failed: Connection closed before receiving a handshake response.
Is there any workaround to either bypass this somehow (can't figure out how exactly) or fix it in any other way? Right now only Bypass button "works".
Thanks in advance.

**Comment by amate** [comment]
It is the known problem that Proxydomo close websocket connection when SSL filter is enabled.
The problem occurs because Proxydomo can't distinguish the Websocket connection from the SSL connection.
You can work around the problem by adding "12.34.56.78:443/" to Bypass.txt.
