### ISSUE TITLE
js's from st.mycdn.me refuse to filter

### ISSUE THREAD

**Issue by mas91180** [amate/Proxydomo#36]
Hi, I'm trying to filter js scripts from this domain https://st.mycdn.me and so far I can't and can't figure out why, here's my filter https://i.imgur.com/2By9S0A.png (let's take a simple script here - https://st.mycdn.me/res/js/app/28f29ec7.js). While it says matched in both url and pattern, it's not replacing anything on this domain (if I change URL pattern to grab anything else it works). All txt from lists are deleted. Can you take a look at this weird issue? Thanks.

**Comment by amate** [comment]
Proxydomo can't understand "Content-Encoding: br", so it can't decompress the website.
Please try to import the following filter.
````
[HTTP headers]
Key = "Accept-Encoding: new filter"
In = FALSE
Out = TRUE
Version = ""
Author = ""
Comment = ""
Active = TRUE
Multi = FALSE
URL = ""
Bounds = ""
Limit = 256
Match = "gzip, deflate, (sdch, |)br"
Replace = "gzip, deflate"
````

**Comment by mas91180** [comment]
Thanks a lot, I tried changing incoming headers at first
