### ISSUE TITLE
Youtube web page not getting filter in Firefox and Chrome

### ISSUE THREAD

**Issue by nhantrn** [amate/Proxydomo#38]
Recently youtube web page is not getting filtered in Firefox and Chrome. Internet Explorer and Edge is ok though.

**Comment by amate** [comment]
Proxydomo can't understand "Content-Encoding: br", so it can't decompress the website.
Please try to import the following filter.
````
[HTTP headers]
Key = "Accept-Encoding: new filter"
In = FALSE
Out = TRUE
Version = ""
Author = ""
Comment = ""
Active = TRUE
Multi = FALSE
URL = ""
Bounds = ""
Limit = 256
Match = "gzip, deflate, (sdch, |)br"
Replace = "gzip, deflate"
````

**Comment by nhantrn** [comment]
Ok, that works.
