### ISSUE TITLE
local.ptron headers

### ISSUE THREAD

**Issue by mas91180** [amate/Proxydomo#39]
Hi Amate, is there any way to change them without re-building the sources? I'd like to add Access-Control-Allow-Origin there for example.
Thanks.

**Comment by amate** [comment]
````
[HTTP headers]
Key = "Access-Control-Allow-Origin: test"
In = TRUE
Out = FALSE
Version = ""
Author = ""
Comment = ""
Active = TRUE
Multi = FALSE
URL = ""
Bounds = ""
Limit = 2000
Match = ""
Replace = "*"

````
Please import this filter.

**Comment by mas91180** [comment]
I tried that, unfortunately, the only headers I can see are (for js file):
HTTP/1.1 200 OK
Content-Type: text/javascript
Content-Length: 7993
Connection: close

See the code at the end of the CRequestManager::_HandleLocalPtron method - _FakeResponse("200 OK", filename);
Those are the only headers in _FakeResponse...

**Comment by amate** [comment]
v1.97 fixed
