### ISSUE TITLE
Proxydomo 64-bit name

### ISSUE THREAD

**Issue by Zero3K** [amate/Proxydomo#41]
It should just be called Proxydomo, not Proxydomo64.

**Comment by amate** [comment]
I will not change the name.
The reason is because the same name can not be created in the same folder.

**Comment by Zero3K** [comment]
People can rename it as they see fit.

**Comment by amate** [comment]
I think people should rename Proxydomo64 to Proxydomo by themselves.

**Comment by Zero3K** [comment]
Yeah, but the name of the actual program shown via Tooltip will still be Proxydomo64. I think that a decent compromise would be to change the name internally but keep the filename as Proxydomo64.exe.
