### ISSUE TITLE
Issue with a website

### ISSUE THREAD

**Issue by Zero3K** [amate/Proxydomo#42]
http://motherless.com (NSFW) doesn't load when using Proxydomo as the HTTP proxy server (even when the Bypass button is clicked on).

**Comment by amate** [comment]
In my environment it successfully connected to the site.
What is written in the log?

**Comment by Zero3K** [comment]
https://pastebin.com/J40xDZ2e

**Comment by amate** [comment]
Please turn on "Use http 1.1 for Proxy connection" in Opera settings

**Comment by Zero3K** [comment]
It is already checked.

EDIT: Even the latest version of Firefox doesn't display it when using Proxydomo as the HTTP proxy.

**Comment by amate** [comment]
Because HTTP 1.0 does not support "Transfer-Encoding: chunked", the connection is disconnected from the server side.
Please use a browser that supports HTTP 1.1 with Proxy connection.

I was able to connect to the site in my environment (FireFox 53).

**Comment by Zero3K** [comment]
Oh, it was because of Ad Muncher not being HTTP 1.1 compliant.
