### ISSUE TITLE
SSL_ERROR_RX_MALFORMED_HANDSHAKE on cnet.com

### ISSUE THREAD

**Issue by nhantrn** [amate/Proxydomo#47]
Getting `SSL_ERROR_RX_MALFORMED_HANDSHAKE` on cnet.com

**Comment by amate** [comment]
I can't reproduce the error.

**Comment by nhantrn** [comment]
I'm getting same error on https://www.pcmag.com too. If bypass Proxydomo, those sites load in fine. I don't see anything in the error log. Is there anyway for me to debug it?

**Comment by amate** [comment]
Wolfssl cause the error because the server side certificate is too big.
It is difficult for me to fix this problem.

**Comment by nhantrn** [comment]
I asked the people at wolfssl forum and they advice to set the `MAX_CERTIFICATE_SZ ` to a larger value using `CFLAGS` at compiling.

You can read it here: https://www.wolfssl.com/forums/post3317.html#p3317

**Comment by amate** [comment]
thx!
v1.100 fixed

**Comment by nhantrn** [comment]
Thanks!
