### ISSUE TITLE
Suggestion: Add Fonts settings for Edit Filter

### ISSUE THREAD

**Issue by mas91180** [amate/Proxydomo#48]
Could you please add the ability to change fonts for Edit Filter and Test Filter dialogs - Pattern and Replacement and both Test Filter windows? Or at least one font for all of them? Just and option to read from settings.ini - like:
[FilterEditWindow]
Font=Courier New,12
...
would be enough. Just settings.ini option, no need to add anything to Options dialog. Thanks in advance!

**Comment by amate** [comment]
v1.101 added
Add the following sentence to settings.ini
```
[FilterEditWindowFont]
lfFaceName=Consolas
pointSize=9
[FilterTestWindowFont]
lfFaceName=Consolas
pointSize=9
```
