### ISSUE TITLE
Proxydomo how to filter some Asian characters

### ISSUE THREAD

**Issue by moonlune** [amate/Proxydomo#49]
I would like to know Proxydomo how to filter some Asian characters, such as Japanese, Chinese ... Older versions can be filtered directly, but now even if the rules are correct, there is no effect! Thank you!

**Comment by amate** [comment]
I can filter by using the following filter in my environment.
````
[Patterns]
Name = "new filter"
Version = ""
Author = ""
Comment = ""
Active = TRUE
Multi = FALSE
URL = ""
Bounds = ""
Limit = 256
Match = "日本語"
Replace = "英語"
````
https://ja.wikipedia.org/wiki/日本語
![default](https://user-images.githubusercontent.com/647810/27992521-6fbc28be-64d1-11e7-8cfd-36b512c56d55.png)

Could you give me an example?

**Comment by moonlune** [comment]
` [Patterns]`
`Name = "new filter"`
`Version = ""`
`Author = ""`
`Comment = ""`
`Active = TRUE`
`Multi = FALSE`
`URL = ""`
`Bounds = ""`
`Limit = 256`
`Match = "日本語"`
`Replace = "英語"`
[https://ja.wikipedia.org/wiki/日本語](url)
I have used the above rules to test the link,and tested several coded pages.In the above link, because the page uses the "UTF-8" encoding, there is no effect!
But for the use of "GB2312" encoded web pages, rules effective!I guess it is caused by the language setting of the operating system?
http://www.guoxue.com/shibu/24shi/sangzz/sgzz_001.htm

**Comment by amate** [comment]
Proxydomo convert from the character code of the original web page to UTF16 before filtering the web page.
Have you enabled SSL/TLS filtering?
Please check the box of web filter debug in the log window and open the following URL.
https://ja.wikipedia.org/wiki/日本語

**Comment by moonlune** [comment]
Thank you very much, the problem has been solved! The reason is that my proxydomo not enabled SSL / TLS filtering, and there is a rule not allow multiple matches. Has been was tested in the "yahoo.co.jp" , the performance is perfect. Thank you for your help!
