### ISSUE TITLE
Connections remain un-closed

### ISSUE THREAD

**Issue by mas91180** [amate/Proxydomo#50]
Hi, starting the latest version (but no more than one or two releases earlier) I noticed that many connections remain un-closed (Abort button doesn't close them) even after I close the browser (note: connections to web-sites I visited). They're piling up and after a week I've got 200+ unclosed connections, when I try to close Proxydomo to reset it, the main window disappears but the process remains so I have to kill it via process manager. I'm under Win8.1 x64. Please check and let me know if you need additional information. See the screenshot
<img src="https://i.imgur.com/aKvoYG2.png"/>

**Comment by amate** [comment]
I can't reproduce the error.

**Comment by mas91180** [comment]
Not every site produces these, but you can see them if you visit this one for example - https://2ch.hk/ja/
Click a few pictures, scroll a few pages (they're loaded via ajax) - 5-10 minutes in and you'll see.

NB Thanks a lot for adding font settings!

**Comment by amate** [comment]
I can't reproduce the error in my environment.
Have you enabled SSL/TLS filtering?

**Comment by mas91180** [comment]
Sure, it's enbled. What I notice is that if I use Remote Proxy (I'm using Telerik's Fiddler for example) - no "ghost" connections... I'm using the latest stable Opera, although it seems it's not relevant...
I have sevaral sites that give me this, but the most reliable one to me is 2ch.hk - after 5 minutes I'll definitely have 2-3 ghost connections to it - 5.61.239.35:443

**Comment by amate** [comment]
v1.102 fixed

**Comment by mas91180** [comment]
Seems like the problem is still there, I just didn't track which web-sites produces those
