### ISSUE TITLE
Secure Connection Failed(SSL_ERROR_RX_UNEXPECTED_SERVER_KEY_EXCH)

### ISSUE THREAD

**Issue by K1GP** [amate/Proxydomo#51]
Proxydomo v1.102 with ssl filtering enabled.
When access https://www.wolfssl.com/wolfSSL/Home.html got this error message.
"Secure Connection Failed
An error occurred during a connection to www.wolfssl.com.
SSL received an unexpected Server Key Exchange handshake message. (Error code: SSL_ERROR_RX_UNEXPECTED_SERVER_KEY_EXCH)"

**Comment by amate** [comment]
I can't reproduce the error.

**Comment by K1GP** [comment]
It's so weid you can't reproduce it because I test this many times under brand new firefoxv50-55.03 with brand new proxydomov1.01 everything is fine but change to proxydomov1.02 the error show again.

**Comment by K1GP** [comment]
It's so weid you can't reproduce it because I test this many times under brand new firefox v50.1.0 and v55.0.3 with brand new proxydomo v1.101 everything is fine but change to proxydomo v1.102 the error show again.

**Comment by amate** [comment]
https://youtu.be/MTMFDHbjdOY

**Comment by K1GP** [comment]
![1](https://user-images.githubusercontent.com/31658680/30138826-f9a160a4-939c-11e7-9432-ac70d51dead1.png)

**Comment by mas91180** [comment]
Have you installed Proxydomo's certificate? I don't see any issues with that web-site either.

**Comment by K1GP** [comment]
Yes, I do have installed the Proxydomo's certificate. Other https sites work just fine. This problem only happens on Proxydomov1.102.
