### ISSUE TITLE
Error on https://www.eso.org/

### ISSUE THREAD

**Issue by nhantrn** [amate/Proxydomo#53]
Error code: SSL_ERROR_RX_UNEXPECTED_SERVER_KEY_EXCH

**Comment by mas91180** [comment]
my 2 coins as another user - I don't see any issues or errors on this site

**Comment by amate** [comment]
I can't reproduce the error in my environment.

**Comment by K1GP** [comment]
I can reproduce it on https://www.eso.org/
 The same error code I see on https://www31.atwiki.jp, https://developer.mozilla.org and https://www.bilibili.com
Now i just simply bypass them because no one can reproduce.
win7x86 + proxydomo1.105 + firefox52.8.1esp firefox61
