### ISSUE TITLE
Corruping text

### ISSUE THREAD

**Issue by mas91180** [amate/Proxydomo#57]
Website - http://w1.c1.rada.gov.ua/pls/radan_gs09/ns_golos?g_id=19678
I know it's incorrect in terms of html standards, but still. How to reproduce - I removed all actual filters (renamed filters.xml) so there were none and ran it with "Web page filter" option checked - got corrupted text (seems like Proxydomo just converted it from windows-1251 to utf-8, but incorrectly anyway), once you uncheck "Web page filter" - everything is normal.
(Sure, I can whitelist it in bypass.txt, but that's not how it should be handled in this case I think)
Can you please check into this?
Thanks

**Comment by amate** [comment]
Please add "w1.c1.rada.gov.ua/$SET(0=3)" to PriorityCharset.txt

**Comment by mas91180** [comment]
Thanks, it works! Never even noticed that file - shame on me! Please check if this is correct translation, probably you'll want to update it with some next release:
```
# 優先する文字コード (Set preferred character encoding)
#
# URL$SET(0=1 or 2 or 3)
#
# 1:ページから文字コードを推定する - Get character encoding from the page
# 2:ページ内の文字コード指定 (<meta charset="?">) - Get character encoding from meta
# 3:レスポンスヘッダのContent-Typeに書いてあるcharset - Use the character encoding set in the Content-Type of the response header
```

**Comment by amate** [comment]
v1.106 update
thx!
