### ISSUE TITLE
$JUMP local.ptron

### ISSUE THREAD

**Issue by K1GP** [amate/Proxydomo#60]
$JUMP local.ptron won't change the location.href 

[HTTP headers]
Key = "URL: Redirect"
In = FALSE
Out = TRUE
Version = ""
Author = ""
Comment = ""
Active = TRUE
Multi = FALSE
URL = ""
Bounds = ""
Limit = 256
Match = "http://www.teamliquid.net"
Replace = "$JUMP(http://local.ptron/index.html)"

index.html copy from blocklistinfo\

**Comment by nhantrn** [comment]
Mostly likely Windows cached the dns and automatically reroute it to the `https://` version so that's why it didn't get matched. Do a `ipconfig /flushdns` in the command prompt to clear it and it'll work.

Or just change your match to:
`Match = "http(s|)://www.teamliquid.net"`

**Comment by K1GP** [comment]
sorry i didn't explain it clearly.
the problem is this filter did work, index.html loaded but the window.location.href and the <script src='/example.js'>  in the local.ptron/index.html point to the origin host www.teamliquid.net.

**Comment by nhantrn** [comment]
In tha case, you have to do the redir in the URL pattern, not the header replacement.

`[HTTP headers]
Key = "URL: Redirect"
In = FALSE
Out = TRUE
Version = ""
Author = ""
Comment = ""
Active = TRUE
Multi = FALSE
URL = "*.teamliquid.net$JUMP(http://www.google.com)"
Bounds = ""
Limit = 256
Match = ""
Replace = ""`

**Comment by K1GP** [comment]
I try it bug still no luck.

**Comment by K1GP** [comment]
I test the filter but still faild.
![fail in proxydomo](https://user-images.githubusercontent.com/31658680/49581128-e4d90b80-f98b-11e8-81c5-ff85b6cbfc9f.png)

The same filter in proxomitron succeed.
![succeed in proxomitron](https://user-images.githubusercontent.com/31658680/49581130-e571a200-f98b-11e8-9a98-10a04b131c97.png)

**Comment by nhantrn** [comment]
What are you trying to do? Do you have to redirect to a local.ptron page?

**Comment by K1GP** [comment]
I just want the address bar and the page show the 'right' location(http://local.ptron/index.html).
yes, I think local page is the best option

**Comment by nhantrn** [comment]
Proxydomo doesn't seem to handle $JUMP redirection to `local.ptron` with a http 302 redirect command. Instead it does a [200](https://github.com/amate/Proxydomo/blob/62556133ebe2e94d31cc05696099efcf846647fd/Proxydomo/RequestManager.cpp#L997). It's an exception to behave like the $RDIR command. I don't know enough to understand why amate did this.

For now, maybe you could redirect to a dummy.html and add to it a <script> with `document.location="http://local.ptron/whateverthatyouwanttodo.html` to make a double hop.

**Comment by K1GP** [comment]
Got it.
Many thanks for your time.

**Comment by WRFan** [comment]
I have the same problem, it seems:

---------------------------------------------------------------------------------------------
[HTTP headers]
Key = ": RESP Error (In)"
In = TRUE
Out = FALSE
Version = ""
Author = ""
Comment = ""
Active = TRUE
Multi = FALSE
URL = ""
Bounds = ""
Limit = 256
Match = "$RESP(*40(3|5))$SET(0=$RDIR(http://local.ptron/403.html))|"
        ""
        "(^$URL(*ipv4.google.com))$RESP(*(400|404|409|410|500|502|520))$SET(0=$RDIR(http://local.ptron/404.html))"
Replace = "\0"
---------------------------------------------------------------------------------------------

If I $RDIR to a web page, instead of local.ptron it works as expected

Hope the developer can fix this

**Comment by amate** [comment]
v1.108 fixed

**Comment by K1GP** [comment]
Thanks for the 108 update.
But like nhantrn said[https://github.com/amate/Proxydomo/issues/62]
1.108 didn't work for http://local.ptron. (302 error)

**Comment by amate** [comment]
v1.109 fixed
