### ISSUE TITLE
Request to non-secure http://local.ptron resources getting 302 errors

### ISSUE THREAD

**Issue by nhantrn** [amate/Proxydomo#62]
Thanks amate for the new update.

Though I ran into a problem where requests to non-secure http://local.ptron resources will result in 302 errors.

Even http://local.ptron/blocklistinfo/ will result in 302 errors.

https works fine.

edit: this is for the new v1.08 if that wasn't clear in my post.

**Comment by amate** [comment]
v1.109 fixed

**Comment by nhantrn** [comment]
👍
