### ISSUE TITLE
Proxydomo high cpu usage after visiting local.ptron/blocklistinfo/

### ISSUE THREAD

**Issue by nhantrn** [amate/Proxydomo#63]
I kind of forgot about this bug, but I've noticed it awhile time ago.
If you have the statistics for block list enabled and visit http://local.ptron/blocklistinfo/, Proxydomo will begin to cause high cpu usage. Event if you exit Proxydomo using the context menu on the tray icon, the tray icon will disappear but the proxydomo.exe process still exist in Task Manager. You can only kill it in Task Manager.

**Comment by amate** [comment]
v1.109 fixed

**Comment by nhantrn** [comment]
👍
