### ISSUE TITLE
32-bit version?

### ISSUE THREAD

**Issue by JeanPaulLucien** [amate/Proxydomo#68]
Can you compile 32-bit version?

**Comment by amate** [comment]
The library used by the software is only available in a 64-bit version, so  I cannot provide a 32-bit executable binary at this time.

**Comment by JeanPaulLucien** [comment]
@amate what library?

**Comment by amate** [comment]
OpenSSL

**Comment by JeanPaulLucien** [comment]
@amate OpenSSL there is for 32-bit. 
libssl-3-x64.dll ?
https://wiki.openssl.org/index.php/Binaries

Can you make 32-bit version without changes? I don't know how to discribe my idea. Just  now I get a message tht this is not 32-bit app. I waant tnt to get any other error.

**Comment by amate** [comment]
https://github.com/amate/Proxydomo/releases/tag/v2.2
Added 32bit binary.

**Comment by JeanPaulLucien** [comment]
Did not work. I tried my lib. Still: "this is not win32".

**Comment by amate** [comment]
What is your OS?
Have you installed VC_redist.x86.exe?
It won't work on XP.

**Comment by JeanPaulLucien** [comment]
@amate you are right I forgot about this. 
See you later!

Not many new in 3.0: https://en.wikipedia.org/wiki/OpenSSL
