### ISSUE TITLE
[report] Chrome v42 will starts marking SHA-1 SSL Certificates as insecure

### ISSUE THREAD

**Issue by nhantrn** [amate/Proxydomo#8]
Ok, I'm going to create a few issues as I've been testing v1.51 for the last day now.
First of, report of "Chrome Version 42 Starts Marking SHA-1 SSL Certificates As Insecure" (https://ma.ttias.be/chrome-version-42-starts-marking-sha-1-ssl-certificates-insecure/).

Probably will create some annoyances for Chrome users.

**Comment by amate** [comment]
v1.52 fixed
thx!
