### ISSUE TITLE
[bug] HTTPS connections from Opera 12.17 and older Firefox does not go through

### ISSUE THREAD

**Issue by nhantrn** [amate/Proxydomo#9]
I'm still using the old Opera 12.17 (last updated in mid 2013) for testing reason, and HTTPS connections doesn't work with Proxydomo v1.51. Connections to secure sites get kill right away, so I don't know what wrong with it. Perhaps protocol breakage. Same problem with old Firefox. I'm using Firefox 26.0.

Here's the log:

```
>>> port 65133 : New request received
>>> port 65133 #2111 : Request received from browser
CONNECT github.com:443 HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:26.0) Gecko/20100101 Firefox/26.0
Proxy-Connection: keep-alive
Connection: keep-alive
Host: github.com

>>> port 65133 #2111 : Response sent to browser
HTTP/1.0 200 Connection established
Proxy-agent: Proxydomo/1.0


>>> port 65133 : Request ended
```

**Comment by amate** [comment]
v1.52 fixed
thx!
